"""refactor: replace mbti with occupation

Revision ID: 026c6a985f37
Revises: bd3761bdd824
Create Date: 2026-02-03 11:59:42.865713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '026c6a985f37'
down_revision: Union[str, Sequence[str], None] = 'bd3761bdd824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('occupation', sa.String(length=32), nullable=True, comment='职业/身份'))
    op.drop_column('user_profiles', 'mbti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('mbti', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4), nullable=True, comment='MBTI人格'))
    op.drop_column('user_profiles', 'occupation')
    # ### end Alembic commands ###
