"""Add custom_images table

Revision ID: 24e983deb802
Revises: 3a46372e07fe
Create Date: 2026-02-04 15:49:37.248928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e983deb802'
down_revision: Union[str, Sequence[str], None] = '3a46372e07fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_images',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='图片存储路径 (相对路径)'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='展示次数'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_images_id'), 'custom_images', ['id'], unique=False)
    op.create_index(op.f('ix_custom_images_user_id'), 'custom_images', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_images_user_id'), table_name='custom_images')
    op.drop_index(op.f('ix_custom_images_id'), table_name='custom_images')
    op.drop_table('custom_images')
    # ### end Alembic commands ###
