"""Initial tables

Revision ID: 3a46372e07fe
Revises: 
Create Date: 2026-02-03 16:34:43.900775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a46372e07fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_index(op.f('ix_system_config_id'), 'system_config', ['id'], unique=False)
    op.create_table('users',
    sa.Column('device_id', sa.String(length=10), nullable=False, comment='6位设备短码'),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('device_secret', sa.String(length=64), nullable=False, comment='HMAC密钥'),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('almanac_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lunar_date', sa.String(length=20), nullable=True),
    sa.Column('ganzhi_year', sa.String(length=10), nullable=True),
    sa.Column('ganzhi_month', sa.String(length=10), nullable=True),
    sa.Column('ganzhi_day', sa.String(length=10), nullable=True),
    sa.Column('favorable', sa.JSON(), nullable=True, comment='宜事项'),
    sa.Column('unfavorable', sa.JSON(), nullable=True, comment='忌事项'),
    sa.Column('lucky_direction', sa.String(length=20), nullable=True),
    sa.Column('lucky_item', sa.String(length=50), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('commentary', sa.Text(), nullable=True, comment='AI批注'),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_user_date')
    )
    op.create_index(op.f('ix_almanac_history_date'), 'almanac_history', ['date'], unique=False)
    op.create_index(op.f('ix_almanac_history_id'), 'almanac_history', ['id'], unique=False)
    op.create_index(op.f('ix_almanac_history_user_id'), 'almanac_history', ['user_id'], unique=False)
    op.create_table('divination_records',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False, comment='本命/客座'),
    sa.Column('intent', sa.String(length=20), nullable=True),
    sa.Column('selected_words', sa.JSON(), nullable=False),
    sa.Column('result_idiom', sa.String(length=50), nullable=True),
    sa.Column('result_interpretation', sa.Text(), nullable=True),
    sa.Column('result_advice', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divination_records_id'), 'divination_records', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birth_datetime', sa.DateTime(), nullable=False),
    sa.Column('birth_place', sa.String(length=100), nullable=True),
    sa.Column('bazi_year', sa.String(length=10), nullable=False),
    sa.Column('bazi_month', sa.String(length=10), nullable=False),
    sa.Column('bazi_day', sa.String(length=10), nullable=False),
    sa.Column('bazi_hour', sa.String(length=10), nullable=False),
    sa.Column('profession', sa.String(length=50), nullable=True),
    sa.Column('focus_areas', sa.JSON(), nullable=True, comment='["事业", "财运"]'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_divination_records_id'), table_name='divination_records')
    op.drop_table('divination_records')
    op.drop_index(op.f('ix_almanac_history_user_id'), table_name='almanac_history')
    op.drop_index(op.f('ix_almanac_history_id'), table_name='almanac_history')
    op.drop_index(op.f('ix_almanac_history_date'), table_name='almanac_history')
    op.drop_table('almanac_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_config_id'), table_name='system_config')
    op.drop_table('system_config')
    # ### end Alembic commands ###
