"""update user_profiles schema

Revision ID: 3bff48ec1187
Revises: 60d41c43a750
Create Date: 2026-02-05 00:48:53.980580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3bff48ec1187'
down_revision: Union[str, Sequence[str], None] = '60d41c43a750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'))
    op.add_column('user_profiles', sa.Column('gender', sa.Integer(), nullable=False, comment='性别: 0女 1男'))
    op.add_column('user_profiles', sa.Column('birth_year', sa.Integer(), nullable=False))
    op.add_column('user_profiles', sa.Column('birth_month', sa.Integer(), nullable=False))
    op.add_column('user_profiles', sa.Column('birth_day', sa.Integer(), nullable=False))
    op.add_column('user_profiles', sa.Column('birth_hour', sa.Integer(), nullable=False, comment='时辰: -1未知, 0-23'))
    op.add_column('user_profiles', sa.Column('is_lunar', sa.Boolean(), nullable=False, comment='是否农历'))
    op.add_column('user_profiles', sa.Column('occupation', sa.String(length=50), nullable=True, comment='职业'))
    op.add_column('user_profiles', sa.Column('notes', sa.Text(), nullable=True, comment='备注/关注点'))
    op.drop_column('user_profiles', 'birth_datetime')
    op.drop_column('user_profiles', 'focus_areas')
    op.drop_column('user_profiles', 'birth_place')
    op.drop_column('user_profiles', 'profession')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profession', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('birth_place', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('focus_areas', mysql.JSON(), nullable=True, comment='["事业", "财运"]'))
    op.add_column('user_profiles', sa.Column('birth_datetime', mysql.DATETIME(), nullable=False))
    op.drop_column('user_profiles', 'notes')
    op.drop_column('user_profiles', 'occupation')
    op.drop_column('user_profiles', 'is_lunar')
    op.drop_column('user_profiles', 'birth_hour')
    op.drop_column('user_profiles', 'birth_day')
    op.drop_column('user_profiles', 'birth_month')
    op.drop_column('user_profiles', 'birth_year')
    op.drop_column('user_profiles', 'gender')
    op.drop_column('user_profiles', 'nickname')
    # ### end Alembic commands ###
