"""Add firmware table

Revision ID: 5a5ded598b4b
Revises: c9cb4718ecaa
Create Date: 2026-02-06 00:30:45.335967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5ded598b4b'
down_revision: Union[str, Sequence[str], None] = 'c9cb4718ecaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmwares',
    sa.Column('version_code', sa.Integer(), nullable=False, comment='整数版本号 (A.B.C.D -> A*1000000 + B*10000 + C*100 + D)'),
    sa.Column('version_str', sa.String(length=20), nullable=False, comment='显示版本号 (如 1.0.0.1)'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='固件文件存储路径'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA-256 校验和'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否可用'),
    sa.Column('description', sa.Text(), nullable=True, comment='版本更新说明'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_str')
    )
    op.create_index(op.f('ix_firmwares_id'), 'firmwares', ['id'], unique=False)
    op.create_index(op.f('ix_firmwares_version_code'), 'firmwares', ['version_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firmwares_version_code'), table_name='firmwares')
    op.drop_index(op.f('ix_firmwares_id'), table_name='firmwares')
    op.drop_table('firmwares')
    # ### end Alembic commands ###
