"""add devices table

Revision ID: 60d41c43a750
Revises: 24e983deb802
Create Date: 2026-02-05 00:30:52.951402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60d41c43a750'
down_revision: Union[str, Sequence[str], None] = '24e983deb802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_code', sa.String(length=6), nullable=False, comment='6位设备码（由UUID通过算法A生成）'),
    sa.Column('init_password_hash', sa.String(length=255), nullable=False, comment='初始密码哈希（由UUID通过算法B生成）'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='ESP32芯片UUID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/activated/disabled'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='激活后关联的用户ID'),
    sa.Column('batch_name', sa.String(length=100), nullable=True, comment='批次名称'),
    sa.Column('activated_at', sa.DateTime(), nullable=True, comment='激活时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.add_column('users', sa.Column('password_set', sa.Boolean(), nullable=False, comment='用户是否已设置自定义密码'))
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True,
               comment='用户自定义密码哈希')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False,
               comment=None,
               existing_comment='用户自定义密码哈希')
    op.drop_column('users', 'password_set')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
