"""init_tables

Revision ID: bd3761bdd824
Revises: 
Create Date: 2026-02-03 10:13:18.824844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3761bdd824'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('device_code', sa.String(length=6), nullable=False, comment='6位设备短码'),
    sa.Column('device_uuid', sa.String(length=64), nullable=True, comment='设备硬件ID hash'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('last_login_at', sa.String(length=32), nullable=True, comment='最后登录时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_code'), 'users', ['device_code'], unique=True)
    op.create_index(op.f('ix_users_device_uuid'), 'users', ['device_uuid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('almanac_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='黄历日期'),
    sa.Column('auspicious', sa.String(length=255), nullable=True, comment='宜'),
    sa.Column('inauspicious', sa.String(length=255), nullable=True, comment='忌'),
    sa.Column('daily_fortune', sa.Text(), nullable=True, comment='今日运势'),
    sa.Column('lucky_color', sa.String(length=32), nullable=True, comment='幸运色'),
    sa.Column('lucky_direction', sa.String(length=32), nullable=True, comment='财神方位'),
    sa.Column('lucky_time', sa.String(length=64), nullable=True, comment='吉时'),
    sa.Column('wealth_score', sa.Integer(), nullable=True, comment='财运分'),
    sa.Column('health_score', sa.Integer(), nullable=True, comment='健康分'),
    sa.Column('love_score', sa.Integer(), nullable=True, comment='桃花分'),
    sa.Column('career_score', sa.Integer(), nullable=True, comment='事业分'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_almanac_history_date'), 'almanac_history', ['date'], unique=False)
    op.create_index(op.f('ix_almanac_history_id'), 'almanac_history', ['id'], unique=False)
    op.create_index(op.f('ix_almanac_history_user_id'), 'almanac_history', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=True, comment='昵称'),
    sa.Column('gender', sa.SmallInteger(), nullable=True, comment='性别: 1男 0女'),
    sa.Column('birth_year', sa.Integer(), nullable=False, comment='出生年'),
    sa.Column('birth_month', sa.Integer(), nullable=False, comment='出生月'),
    sa.Column('birth_day', sa.Integer(), nullable=False, comment='出生日'),
    sa.Column('birth_hour', sa.Integer(), nullable=True, comment='出生时辰(0-23, -1未知)'),
    sa.Column('is_lunar', sa.Boolean(), nullable=True, comment='是否为农历生日'),
    sa.Column('mbti', sa.String(length=4), nullable=True, comment='MBTI人格'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_almanac_history_user_id'), table_name='almanac_history')
    op.drop_index(op.f('ix_almanac_history_id'), table_name='almanac_history')
    op.drop_index(op.f('ix_almanac_history_date'), table_name='almanac_history')
    op.drop_table('almanac_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_device_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_device_code'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
